/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Movimentacao;
import DAO.connectDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class CadMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form Movimentacao
     */
    public CadMovimentacao() {
        initComponents();
    }
    
    String operacaoAtivaGlobal = "Nenhum";
    public CadMovimentacao(String operacaoAtiva){
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        //INCLUSÃO
        if(operacaoAtiva.equals(operacao)){
            SetFormVisible(true);
            jButton1.setText(operacaoAtivaGlobal);
        }
        operacao = "Alterar";
        if(operacaoAtiva.equals(operacao)){
            SetFormVisible(false);
            jButton1.setText("Pesquisar");
        }
        operacao = "Excluir";
        if(operacaoAtiva.equals(operacao)){
            SetFormVisible(false);
            jButton1.setText("Pesquisar");
        }
    }

    Movimentacao m = new Movimentacao();
    String tipoCartao = "";
    
    //UTEIS
    private void SetFormVisible(Boolean bool){
        jLabel1.setVisible(bool);
        jLabel2.setVisible(bool);
        jLabel3.setVisible(bool);
        jLabel4.setVisible(bool);
        jLabel5.setVisible(bool);
        jLabel6.setVisible(bool);
        jLabel7.setVisible(bool);
        jLabel8.setVisible(bool);
        jLabel9.setVisible(bool);
        jTextField1.setVisible(bool);
        jTextField2.setVisible(bool);
        jTextField3.setVisible(bool);
        jTextField4.setVisible(bool);
        jRadioButton1.setVisible(bool);
        jRadioButton2.setVisible(bool);
        jTextField5.setVisible(bool);
        jTextField6.setVisible(bool);
        jTextField7.setVisible(bool);
        jTextField8.setVisible(bool);
    }
    
    private void ClearFormInputs(){
        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }
    
    private void SetFormEditable(boolean bool){
        jTextField1.setEditable(bool);
        jTextField2.setEditable(bool);
        jTextField3.setEditable(bool);
        jTextField4.setEditable(bool);
        jRadioButton1.setEnabled(bool);
        jRadioButton2.setEnabled(bool);
        jTextField5.setEditable(bool);
        jTextField6.setEditable(bool);
        jTextField7.setEditable(bool);
        jTextField8.setEditable(bool);
    }
    
    private void SetFormValues(){       
        jTextField1.setText(m.getNum_age()); 
        jTextField2.setText(m.getNum_conta());
        jTextField3.setText(m.getData_mov());
        jTextField4.setText(m.getDocumento());
        if(m.getCreditoDebito().equalsIgnoreCase("c"))
            jRadioButton1.setSelected(false);
        else if(m.getCreditoDebito().equalsIgnoreCase("d"))
            jRadioButton2.setSelected(false);
        jTextField5.setText(Integer.toString(m.getId_his()));
        jTextField6.setText(m.getCompl_hist());
        jTextField7.setText(Double.toString(m.getValor()));
        jTextField8.setText(Double.toString(m.getSaldo()));
    }
    
    private void SetMovimentacaoObjectValues(){
        m.setNum_age(jTextField1.getText());
        m.setNum_conta(jTextField2.getText());
        m.setData_mov(jTextField3.getText());
        m.setDocumento(jTextField4.getText());
        if(jRadioButton1.isSelected())
            m.setCreditoDebito("c");
        else if(jRadioButton2.isSelected())
            m.setCreditoDebito("d");
        else
            m.setCreditoDebito(null);
        m.setId_his(Integer.parseInt(jTextField5.getText()));
        m.setCompl_hist(jTextField6.getText());
        m.setValor(Double.parseDouble(jTextField7.getText()));
        m.setSaldo(Double.parseDouble(jTextField8.getText()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnLer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número da Conta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 6, 150, -1));

        jLabel2.setText("Número da Agência");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 34, 150, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 62, 150, -1));

        jLabel3.setText("Documento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel4.setText("Data de Movimentação");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 66, -1, 20));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 90, 150, -1));

        jLabel5.setText("Tipo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 120, -1, -1));

        jRadioButton1.setText("Crédito");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 118, -1, -1));

        jRadioButton2.setText("Débito");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 118, -1, -1));

        jLabel6.setText("Id do Histórico");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 148, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 145, 150, -1));

        jLabel7.setText("Complemento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 176, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 173, 150, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 201, 150, -1));

        jLabel8.setText("Valor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 204, -1, -1));

        jLabel9.setText("Saldo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 232, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 229, 150, -1));

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, -1, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 271, -1, -1));

        btnLer.setText("Ler");
        btnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerActionPerformed(evt);
            }
        });
        getContentPane().add(btnLer, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 271, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            SetMovimentacaoObjectValues();
            if(m.getIsValid()){
                //Inserção no banco de dados
                connectDAO objcon = new connectDAO();
                objcon.connectDB();
                objcon.insereRegistroJFBD("MOVIMENTACAO", m.dadosSQLValues());
                ClearFormInputs();
            }
            else{
                m.ShowErrorValidateMessage("Campos preenchidos incorretamente");
                m.setIsValid(true);
            }
        }
        operacao = "Alteração";
        if(operacaoAtivaGlobal.equals((operacao))){
            SetMovimentacaoObjectValues();
            //ALteração no banco de dados
            if(m.getIsValid()){
                //Inserção no banco de dados
                connectDAO objcon = new connectDAO();
                objcon.connectDB();
                objcon.alteraRegistroJFDB("MOVIMENTACAO", m.alteraDadosSQLValues(), 
                "ID_HIS=" +jTextField1.getText());
                
                //Limpando todos os textos
                ClearFormInputs();
                SetFormVisible(false);
                jButton1.setText("Pesquisar");
                operacaoAtivaGlobal = "Alterar";
                return;
            }
            else{
                m.ShowErrorValidateMessage("Campos preenchidos incorretamente");
                m.setIsValid(true);
            }
        }
        
        operacao = "Alterar";
        if(operacaoAtivaGlobal.equals((operacao))){
            //Pesquisa o clinte com o ID especificado
            connectDAO objcon = new connectDAO();
            m = objcon.pesquisaMovimentacaoJFDB("MOVIMENTACAO", "ID_HIS = '" + jTextField1.getText() + "'");
            
            if(m != null){
                SetFormValues();
                SetFormVisible(true);
                jButton1.setText("Alterar");
                operacaoAtivaGlobal = "Alteração";
            }
            return;
        }
        
        operacao = "Exclusão";
        if(operacaoAtivaGlobal.equals((operacao))){
            connectDAO objcon = new connectDAO();
            objcon.excluiRegistroJFDB("MOVIMENTACAO","ID_HIS=" + jTextField1.getText());

            //Limpando todos os textos
            ClearFormInputs();
            SetFormVisible(false);
            SetFormEditable(true);
            
            jButton1.setText("Pesquisar");
            operacaoAtivaGlobal = "Excluir";
            return;
        }
        
        operacao = "Excluir";
        if(operacaoAtivaGlobal.equals((operacao))){
            //Pesquisa o cliente com o ID especificado
            connectDAO objcon = new connectDAO();
            m = objcon.pesquisaMovimentacaoJFDB("MOVIMENTACAO", "ID_HIS = '" + jTextField1.getText() + "'");
            if(m != null){
                //Mostrando os campos para que possam ser alterados
                jButton1.setText("Excluir");
                operacaoAtivaGlobal = "Exclusão";
                SetFormValues();
                SetFormVisible(true);
                SetFormEditable(false);
            }
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       if(jRadioButton1.isSelected())
       {
           jRadioButton2.setSelected(false);
           tipoCartao = "c";
       }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected())
       {
           jRadioButton1.setSelected(false);
           tipoCartao = "d";
       }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        jTextField5.setText("");
//        jTextField6.setText("");
//        jTextField7.setText("");
//        jTextField8.setText("");
//        jRadioButton1.setSelected(false);
//        jRadioButton2.setSelected(false);
//        tipoCartao = "";
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerActionPerformed
      
    }//GEN-LAST:event_btnLerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLer;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
