/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import DAO.Cliente;
import DAO.connectDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author Alunos
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }
    String operacaoAtivaGlobal = "Nenhum";
    public Clientes(String operacaoAtiva){
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        //INCLUSÃO
        if(operacaoAtiva.equals(operacao)){
            SetFormVisible(true);
            jButton1.setText(operacaoAtivaGlobal);
        }
        operacao = "Alterar";
        if(operacaoAtiva.equals(operacao)){
            SetFormVisible(false);
            jButton1.setText("Pesquisar");;
        }
    }
    
    Cliente dados_cliente = new Cliente();
    String identificacao = "";
    
    char sexoSelecionado = ' ';
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTextField2 = new javax.swing.JTextField();
        JTextField3 = new javax.swing.JTextField();
        JTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JTextField5 = new javax.swing.JTextField();
        JTextField6 = new javax.swing.JTextField();
        JTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        JComboBox = new javax.swing.JComboBox<>();
        JTextField1 = new javax.swing.JTextField();
        JTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JTextField12 = new javax.swing.JTextField();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Id do Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 117, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome do Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 117, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Endereço do Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 117, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Número");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 143, 117, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bairro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 182, 117, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cidade");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 221, 117, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CEP");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 117, 30));

        JTextField2.setBackground(new java.awt.Color(204, 204, 204));
        JTextField2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(JTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 64, 192, 30));

        JTextField3.setBackground(new java.awt.Color(204, 204, 204));
        JTextField3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(JTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 103, 192, 30));

        JTextField4.setBackground(new java.awt.Color(204, 204, 204));
        JTextField4.setForeground(new java.awt.Color(51, 51, 51));
        JTextField4.setToolTipText("");
        getContentPane().add(JTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 142, 90, 30));

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jButton3.setText("Ler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        JTextField5.setBackground(new java.awt.Color(204, 204, 204));
        JTextField5.setForeground(new java.awt.Color(51, 51, 51));
        JTextField5.setToolTipText("");
        getContentPane().add(JTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 181, 192, 30));

        JTextField6.setBackground(new java.awt.Color(204, 204, 204));
        JTextField6.setForeground(new java.awt.Color(51, 51, 51));
        JTextField6.setToolTipText("");
        getContentPane().add(JTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 220, 192, 30));

        JTextField7.setBackground(new java.awt.Color(204, 204, 204));
        JTextField7.setForeground(new java.awt.Color(51, 51, 51));
        JTextField7.setToolTipText("");
        getContentPane().add(JTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 259, 100, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Telefone");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 117, 30));

        JTextField9.setBackground(new java.awt.Color(204, 204, 204));
        JTextField9.setForeground(new java.awt.Color(51, 51, 51));
        JTextField9.setToolTipText("");
        getContentPane().add(JTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 340, 134, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CPF/CNPJ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 117, 30));

        JTextField10.setBackground(new java.awt.Color(204, 204, 204));
        JTextField10.setForeground(new java.awt.Color(51, 51, 51));
        JTextField10.setToolTipText("");
        getContentPane().add(JTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 171, 30));

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Estado do Cliente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 259, 117, 30));

        JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(JComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 259, -1, 30));

        JTextField1.setBackground(new java.awt.Color(204, 204, 204));
        JTextField1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(JTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 25, 90, 30));

        JTextField11.setBackground(new java.awt.Color(204, 204, 204));
        JTextField11.setForeground(new java.awt.Color(51, 51, 51));
        JTextField11.setToolTipText("");
        getContentPane().add(JTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 297, 171, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Complemento");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 297, 117, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Data de Nascimento");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 297, 117, 30));

        JTextField12.setBackground(new java.awt.Color(204, 204, 204));
        JTextField12.setForeground(new java.awt.Color(51, 51, 51));
        JTextField12.setToolTipText("");
        getContentPane().add(JTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 297, 171, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetFormVisible(Boolean bool){
        jLabel1.setVisible(!bool);
        JTextField1.setVisible(!bool);
        jLabel2.setVisible(bool);
        jLabel3.setVisible(bool);
        jLabel4.setVisible(bool);
        jLabel5.setVisible(bool);
        jLabel6.setVisible(bool);
        jLabel7.setVisible(bool);
        jLabel9.setVisible(bool);
        jLabel10.setVisible(bool);
        jLabel12.setVisible(bool);
        jLabel13.setVisible(bool);
        jLabel14.setVisible(bool);
        JTextField2.setVisible(bool);
        JTextField3.setVisible(bool);
        JTextField4.setVisible(bool);
        JTextField5.setVisible(bool);
        JTextField6.setVisible(bool);
        JTextField7.setVisible(bool);
        JTextField9.setVisible(bool);
        JTextField10.setVisible(bool);
        JTextField11.setVisible(bool);
        JTextField12.setVisible(bool);
        JComboBox.setVisible(bool);
    }
    
    private void ClearFormInputs(){
        JTextField1.setText("");
        JTextField2.setText("");
        JTextField3.setText("");
        JTextField4.setText("");
        JTextField5.setText("");
        JTextField6.setText("");
        JTextField7.setText("");
        JTextField9.setText("");
        JTextField10.setText("");
        JTextField11.setText("");
        JTextField12.setText("");
        JComboBox.setSelectedIndex(0);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Gravar os dados no objeto cliente c
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            //dados_cliente.setId_cli(JTextField1.getText().isBlank() || JTextField1.getText().isEmpty() ? 0 : Integer.parseInt(JTextField1.getText()));
            dados_cliente.setNome(JTextField2.getText());
            dados_cliente.setEndereco(JTextField3.getText());
            dados_cliente.setNumero(JTextField4.getText());
            dados_cliente.setBairro(JTextField5.getText());
            dados_cliente.setCidade(JTextField6.getText());
            dados_cliente.setCep(JTextField7.getText());
            dados_cliente.setTelefone(JTextField9.getText());
            dados_cliente.setComplemento(JTextField11.getText());
            dados_cliente.setDataNascimento(JTextField12.getText());
            
            switch (JTextField10.getText().length()) {
                case 11:
                    //CPF
                    dados_cliente.setCpf(JTextField10.getText());
                    identificacao = "cpf";
                    break;
                case 14:
                    //CNPJ
                    dados_cliente.setCnpj(JTextField10.getText());
                    identificacao = "cnpj";
                    break;
            }
            if(JComboBox.getSelectedItem().toString() != "ESTADO"){
                dados_cliente.setUf(JComboBox.getSelectedItem().toString());
            }
            JOptionPane.showMessageDialog(null, "Cadastrado");
            
            //Inserção no banco de dados
            connectDAO objcon = new connectDAO();
            objcon.connectDB();
            objcon.insereRegistroJFBD("CLIENTES", dados_cliente.dadosSQLValues());
            ClearFormInputs();
        }
        
        operacao = "Alteração";
        if(operacaoAtivaGlobal.equals((operacao))){
            connectDAO objcon = new connectDAO();
            /*Definindo os valores do objeto Cliente como os valores dos campos */
            dados_cliente.setId_cli(JTextField1.getText().isBlank() || JTextField1.getText().isEmpty() ? 0 : Integer.parseInt(JTextField1.getText()));
            dados_cliente.setNome(JTextField2.getText());
            dados_cliente.setEndereco(JTextField3.getText());
            dados_cliente.setNumero(JTextField4.getText());
            dados_cliente.setBairro(JTextField5.getText());
            dados_cliente.setCidade(JTextField6.getText());
            dados_cliente.setCep(JTextField7.getText());
            dados_cliente.setTelefone(JTextField9.getText());
            dados_cliente.setComplemento(JTextField11.getText());
            dados_cliente.setDataNascimento(JTextField12.getText());
            
            //Verificando se o campo preenchido foi CPF ou CNPJ
            switch (JTextField10.getText().length()) {
               case 11:
                   //CPF
                   dados_cliente.setCpf(JTextField10.getText());
                   identificacao = "cpf";
                   break;
               case 14:
                   //CNPJ
                   dados_cliente.setCnpj(JTextField10.getText());
                   identificacao = "cnpj";
                   break;
               }
                //Definindo o valor do comboBox estado
               dados_cliente.setUf(JComboBox.getSelectedItem().toString());
            
               //ALteração no banco de dados
                objcon.alteraRegistroJFDB("CLIENTES", dados_cliente.alteraDadosSQLValues(), 
                        "ID_CLI=" +JTextField1.getText());

                //Limpando todos os textos
                ClearFormInputs();
                SetFormVisible(false);
                jButton1.setText("Pesquisar");
                operacaoAtivaGlobal = "Alterar";
                return;
        }
        
        operacao = "Alterar";
        if(operacaoAtivaGlobal.equals((operacao))){
            //Pesquisa o clinte com o ID especificado
            connectDAO objcon = new connectDAO();
            dados_cliente = objcon.pesquisaClienteJFDB("CLIENTES", "ID_CLI = '" + JTextField1.getText() + "'");
            
            JTextField2.setText(dados_cliente.getNome());
            JTextField3.setText(dados_cliente.getEndereco());
            JTextField4.setText(dados_cliente.getNumero());
            JTextField5.setText(dados_cliente.getBairro());
            JTextField6.setText(dados_cliente.getCidade());
            JTextField7.setText(dados_cliente.getCep());
            JTextField9.setText(dados_cliente.getTelefone());
            
            if(dados_cliente.getCpf() != null){
                JTextField10.setText(dados_cliente.getCpf());
            }
            else if(dados_cliente.getCnpj() != null){
                JTextField10.setText(dados_cliente.getCnpj());
            }
            JTextField11.setText(dados_cliente.getComplemento());
            JTextField12.setText(dados_cliente.getDataNascimento());
            JComboBox.setSelectedItem(dados_cliente.getUf());
            
            //Mostrando os campos para que possam ser alterados
            
            jButton1.setText("Alterar");
            operacaoAtivaGlobal = "Alteração";
            SetFormVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Botão de Limpar
        ClearFormInputs();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBox;
    private javax.swing.JTextField JTextField1;
    private javax.swing.JTextField JTextField10;
    private javax.swing.JTextField JTextField11;
    private javax.swing.JTextField JTextField12;
    private javax.swing.JTextField JTextField2;
    private javax.swing.JTextField JTextField3;
    private javax.swing.JTextField JTextField4;
    private javax.swing.JTextField JTextField5;
    private javax.swing.JTextField JTextField6;
    private javax.swing.JTextField JTextField7;
    private javax.swing.JTextField JTextField9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
