@baseURL = http://localhost:3000/api/usuarios
###
# @prompt senha

POST {{baseURL}}
Content-Type: application/json

{
    "nome" : "Zée",
    "email" : "ze@uol.com.br",
    "senha" : "{{senha}}"
}

###
# @prompt senha
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "ze@uol.com.br",
    "senha" : "{{senha}}"
}

//Senha Fate@2025*
