@baseURL = http://localhost:3000/api/usuarios
###
# @prompt senha

POST {{baseURL}}
Content-Type: application/json

{
    "nome" : "Alberto Einstein",
    "email" : "loginho@fatec.gov.br",
    "senha" : "{{senha}}"
}

###
# @prompt senha
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "loginho@fatec.gov.br",
    "senha" : "{{senha}}"
}

//Senha Login1*
